/**
 * The extension build (§5.2). A wiring file: the manifests are `src/build/manifest.ts`, what the HUD hook writes is
 * `src/build/artifact.ts`, and both are unit-tested. MV3 is forced, because WXT defaults Firefox and Safari to MV2.
 *
 * `wxt dev` is deliberately not used: it force-adds `tabs` and `scripting`, runs a throwaway profile, does not watch
 * `hud/`, and covers neither Safari nor Orion (§5.2). Builds are `wxt build -b chrome|firefox|safari --mode store|dev`.
 */
import { readFileSync, renameSync, writeFileSync } from "node:fs";
import { basename, dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { defineConfig } from "wxt";
import { sourcesZipName, zipName } from "../scripts/release/artifacts.ts";
import { bundle } from "../skills/coach-pokerogue/scripts/hud-bundle.mjs";
import { DEV_PORT, STORE_PORT } from "../src/protocol/version.ts";
import type { Flavour, Target } from "../src/protocol/wire.ts";
import { BUILD_PLACEHOLDER, buildId, hudScript, notices, stamp, walk } from "./src/build/artifact.ts";
import { SAFARI_BACKGROUND, manifestFor, storeVersion } from "./src/build/manifest.ts";

const root = fileURLToPath(new URL(".", import.meta.url));
const repo = join(root, "..");
const version = storeVersion(JSON.parse(readFileSync(join(root, "package.json"), "utf8")).version);

/** Anything but the dev flavour is a store build: a plain `wxt build` must never produce a dev artifact (§5.4). */
const flavourOf = (mode: string): Flavour => (mode === "dev" ? "dev" : "store");

const targetOf = (browser: string): Target => {
  if (browser === "firefox" || browser === "safari") return browser;
  // Orion installs the Chrome or the Firefox build; it is never a target of its own (§2).
  if (browser !== "chrome") throw new Error(`unknown target browser ${browser}; build -b chrome|firefox|safari`);
  return "chrome";
};

export default defineConfig({
  srcDir: ".",
  imports: false,
  manifestVersion: 3,
  mode: "store",
  // `.output/<browser>-mv3-store` and `-dev`, so a store and a dev build of one browser never overwrite each other.
  outDirTemplate: "{{browser}}-mv{{manifestVersion}}-{{mode}}",
  manifest: ({ browser, mode }) => manifestFor({ target: targetOf(browser), flavour: flavourOf(mode), version }),
  vite: ({ browser, mode }) => ({
    define: {
      COACHEMON_BUILD: JSON.stringify(BUILD_PLACEHOLDER),
      // The whole URL, not a port: the store artifact then holds `ws://127.0.0.1:47147/` literally and the dev port
      // never appears in it at all, which is what the guard checks either way (§5.5).
      COACHEMON_HUB_URL: JSON.stringify(`ws://127.0.0.1:${flavourOf(mode) === "dev" ? DEV_PORT : STORE_PORT}/`),
      COACHEMON_TARGET: JSON.stringify(targetOf(browser)),
      COACHEMON_FLAVOUR: JSON.stringify(flavourOf(mode)),
      COACHEMON_VERSION: JSON.stringify(version),
    },
  }),
  zip: {
    // `{{version}}` is the manifest's, so the stamped `package.json`'s three numbers. Only store builds are ever
    // zipped, so no mode suffix is needed. `zip:extension:done` below renames whatever this writes to what `zipName`
    // says, which is the one name an artifact has (§14.2); the template only has to tell the browsers apart.
    artifactTemplate: "coachemon-{{browser}}-{{version}}.zip",
    sourcesTemplate: sourcesZipName("{{version}}"),
    // The AMO sources zip (§5.7): the repo root, limited to what `npx wxt build -b firefox` actually needs.
    sourcesRoot: "..",
    includeSources: [
      "extension/**",
      "src/protocol/**",
      "src/page/**",
      "src/enums/generated.ts",
      // This config imports it for the artifact names, so `wxt build` inside the zip needs it to load at all (§5.7).
      "scripts/release/artifacts.ts",
      "skills/coach-pokerogue/scripts/hud-bundle.mjs",
      "skills/coach-pokerogue/scripts/hud/**",
      "LICENSE",
      "THIRD_PARTY_NOTICES.md",
      "SOURCES.md",
    ],
    // `.wxt/` is regenerated by the reviewer's own `wxt build`, so shipping it would only be confusing.
    excludeSources: ["extension/.output/**", "extension/node_modules/**", "extension/.wxt/**"],
  },
  hooks: {
    /**
     * The HUD bypasses WXT's bundler: `bundle("hud")` is written as `hud.js` exactly as the skill produces it, but
     * wrapped and comment-stripped (§5.2). The HUD tests keep exercising the raw `bundle()`.
     */
    "build:publicAssets": (_wxt, files) => {
      files.push(
        { relativeDest: "hud.js", contents: hudScript(bundle("hud")) },
        // Both shipped in every artifact, because `hud.js` goes out comment-stripped (§15).
        { relativeDest: "LICENSE", contents: readFileSync(join(repo, "LICENSE"), "utf8") },
        {
          relativeDest: "THIRD_PARTY_NOTICES.md",
          contents: notices(readFileSync(join(repo, "THIRD_PARTY_NOTICES.md"), "utf8"), version),
        },
      );
    },
    /**
     * WXT normalises an MV3 background to a service worker. Safari's must be `scripts` (§5.3), so it goes back in
     * after generation; Firefox's WXT already writes as an event page by itself.
     */
    "build:manifestGenerated": (wxt, manifest) => {
      if (wxt.config.browser === "safari") (manifest as Record<string, unknown>).background = SAFARI_BACKGROUND;
    },
    /** The build id is a hash over `hud.js` and `page.js`, so it can only be stamped once both exist (§5.2). */
    "build:done": wxt => {
      const out = wxt.config.outDir;
      const build = buildId(version, ["hud.js", "page.js"].map(f => readFileSync(join(out, f), "utf8")));
      // Every `.js` the bundler produced, wherever it put it, so no chunk keeps the placeholder.
      for (const rel of walk(out, name => name.endsWith(".js"))) {
        const path = join(out, rel);
        const before = readFileSync(path, "utf8");
        const after = stamp(before, build);
        if (after !== before) writeFileSync(path, after);
      }
      wxt.logger.info(`Coachemon build ${build}`);
    },
    /**
     * `artifactTemplate` cannot branch on the browser, and Safari's artifact is named for what it holds rather than
     * for the browser: §14.6 unzips it and hands the folder to `xcrun safari-web-extension-packager`. So the one name
     * the template cannot write is written here (§14.2).
     */
    "zip:extension:done": (wxt, zipPath) => {
      const named = join(dirname(zipPath), zipName(targetOf(wxt.config.browser), version));
      if (named !== zipPath) renameSync(zipPath, named);
      wxt.logger.info(`Coachemon artifact ${basename(named)}`);
    },
  },
});
