#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: the hand-made 1.0.0 listings (§14.4 of docs/spec/extension-distribution.md).
#
# Order is forced by the release pipeline, not by taste. `extension/.releaserc.json` runs
# `submit-extension.ts --verify` in `verifyRelease`, and `submitsToStores` is `major >= 1`, so
# extension-v1.0.0 itself submits through the API and refuses to release at all while any of the six
# credentials is missing. Everything a store can only give a human therefore happens before 1.0.0 is cut.
#
# Chrome is the only store with a chicken-and-egg: the API needs an item id, and an item id only exists
# once a human has uploaded a package. So the item is created from the newest 0.x zip and left as a draft;
# CI uploads 1.0.0 over it. AMO has no such problem — the add-on id is the gecko id in the manifest, and the
# first API upload creates the add-on.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=12

# Captured values are secrets, and this repo does not ignore `.env`, so they are kept outside the checkout.
ENV_FILE="${ENV_FILE:-$HOME/.coachemon-listing.env}"
touch "$ENV_FILE" && chmod 600 "$ENV_FILE"

REPO="IIxauII/coachemon"
DOCS="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
WORK="${TMPDIR:-/tmp}/coachemon-listing"
mkdir -p "$WORK"

banner "Coachemon 1.0.0: the public listings"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Preflight"
say "Three things must already be true before a store sees anything."
if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
  say "✓ gh is authenticated"
else
  warn "gh is not authenticated — run 'gh auth login' in another terminal, then come back"
fi
if [[ "$(curl -sI https://iixauii.github.io/coachemon/PRIVACY | head -1)" == *200* ]]; then
  say "✓ the privacy policy resolves (both forms ask for that URL)"
else
  warn "https://iixauii.github.io/coachemon/PRIVACY does not return 200 — turn GitHub Pages on for master / root first"
fi
note "Screenshots must be the current HUD. If the panel changed since the last redraw:"
note "  npm run listing:render   (then commit the diff)"
say ""
say "The copy you will paste lives in the repo, not in this wizard:"
note "  $DOCS/docs/listing/description.md      — title, summary, body"
note "  $DOCS/docs/listing/store-disclosure.md — every form answer, in the words they get filed in"
note "  $DOCS/docs/listing/assets/             — screenshots and promo tiles"
pause "Ready?"

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Chrome Web Store: developer account"
say "A one-time \$5 registration fee, paid once per Google account."
open_url "https://chrome.google.com/webstore/devconsole"
step "Sign in as the account that will own the listing, and pay the registration fee."
step "Finish publisher verification: it asks for a contact email and a verification click."
step "Open the Account tab in the left sidebar and find 'Publisher ID'."
ask CWS_PUBLISHER_ID "Paste the Publisher ID:"
write_env CWS_PUBLISHER_ID "$CWS_PUBLISHER_ID"

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Chrome Web Store: create the item"
say "The item is created from the newest 0.x zip purely to mint an item id. It stays a draft:"
say "CI uploads the real 1.0.0 package over it in stage 10."
LATEST_TAG=$(gh release list --repo "$REPO" --limit 30 --json tagName --jq '[.[].tagName | select(startswith("extension-v"))] | first' 2>/dev/null || true)
if [[ -n "${LATEST_TAG:-}" ]]; then
  say "Newest extension release: $LATEST_TAG"
  if gh release download "$LATEST_TAG" --repo "$REPO" --pattern 'coachemon-chrome-*.zip' --dir "$WORK" --clobber >/dev/null 2>&1; then
    say "✓ downloaded to $WORK"
    open_url "file://$WORK"
  else
    warn "could not download the zip; grab it from the release page by hand"
    open_url "https://github.com/$REPO/releases/tag/$LATEST_TAG"
  fi
else
  warn "no extension-v* release found; download coachemon-chrome-<v>.zip by hand"
fi
open_url "https://chrome.google.com/webstore/devconsole"
step "Click 'Add new item' and upload coachemon-chrome-<v>.zip from $WORK."
step "When it lands you are on the item's page. The id is the long lowercase string in the URL,"
step "  .../devconsole/<publisher>/<EXTENSION ID>/edit — that is what CI uploads against."
warn "Do not click 'Submit for review' yet. Save the draft only."
ask CWS_EXTENSION_ID "Paste the extension ID:"
write_env CWS_EXTENSION_ID "$CWS_EXTENSION_ID"

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Chrome Web Store: fill the listing and the privacy tab"
say "Every answer is written down already. Paste, don't compose."
open_url "file://$DOCS/docs/listing/description.md"
open_url "file://$DOCS/docs/listing/store-disclosure.md"
open_url "file://$DOCS/docs/listing/assets"
step "Store listing tab: name 'Coachemon', the summary, the description body, category"
step "  'Workflow & Planning', language English, homepage and support email from the disclosure."
step "Upload the four 1280×800 screenshots, the 440×280 small tile and the 1400×560 marquee."
step "Privacy tab: single purpose, the pokerogue.net host-access justification, and"
step "  remote code = Yes with its justification — the HUD import()s the game's own modules."
step "Data usage: website content only; tick all three certifications; privacy URL"
step "  https://iixauii.github.io/coachemon/PRIVACY"
warn "Still no 'Submit for review'. The draft just has to be complete."
pause "Draft saved?"

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Google Cloud: the service account CI authenticates as"
say "Chrome Web Store API v2 authenticates as a GCP service account — not the old client id and refresh token."
open_url "https://console.cloud.google.com/projectcreate"
step "Create a project (any name; 'coachemon-release' does)."
open_url "https://console.cloud.google.com/apis/library/chromewebstore.googleapis.com"
step "Enable the Chrome Web Store API in that project."
open_url "https://console.cloud.google.com/iam-admin/serviceaccounts/create"
step "Create a service account (no roles needed — the Web Store grants it separately)."
step "Open it → Keys → Add key → Create new key → JSON. The file downloads once."
ask CWS_KEY_JSON "Path to the downloaded JSON key:"
CWS_KEY_JSON="${CWS_KEY_JSON/#\~/$HOME}"
if [[ -f "$CWS_KEY_JSON" ]] && command -v node >/dev/null 2>&1; then
  CWS_SERVICE_ACCOUNT_EMAIL=$(node -e 'process.stdout.write(JSON.parse(require("fs").readFileSync(process.argv[1],"utf8")).client_email||"")' "$CWS_KEY_JSON")
  CWS_SERVICE_ACCOUNT_PRIVATE_KEY=$(node -e 'process.stdout.write(JSON.parse(require("fs").readFileSync(process.argv[1],"utf8")).private_key||"")' "$CWS_KEY_JSON")
  say "✓ read client_email and private_key out of the key file"
else
  warn "could not read that file with node; paste the two fields instead"
  ask CWS_SERVICE_ACCOUNT_EMAIL "client_email:"
  ask_secret CWS_SERVICE_ACCOUNT_PRIVATE_KEY "private_key (the whole -----BEGIN...----- block):"
fi
write_env CWS_SERVICE_ACCOUNT_EMAIL "$CWS_SERVICE_ACCOUNT_EMAIL"
note "the private key is never written to $ENV_FILE; it goes straight to the GitHub secret in stage 9"
say "Service account: $CWS_SERVICE_ACCOUNT_EMAIL"

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Chrome Web Store: let the service account publish"
say "The key alone reaches nothing: the Web Store account has to know it."
open_url "https://chrome.google.com/webstore/devconsole"
step "Account → Users (or the item's 'Users' section) → add this address:"
say "  $CWS_SERVICE_ACCOUNT_EMAIL"
step "Give it the permission that can upload and publish the item."
pause "Added?"

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "AMO: developer account"
say "Free. Two-factor authentication is mandatory for add-on developers."
open_url "https://addons.mozilla.org/developers/"
step "Sign in with a Mozilla account and turn on 2FA if it asks."
note "No add-on is created here. The add-on id is already fixed in the manifest —"
note "  coachemon@iixauii.github.io — and CI's first upload creates the listing under it."
pause "Signed in?"

# ── 8 ─────────────────────────────────────────────────────────────────────
stage "AMO: API credentials"
open_url "https://addons.mozilla.org/developers/addon/api/key/"
step "Generate new credentials. The secret is shown exactly once — copy it before leaving the page."
ask AMO_JWT_ISSUER "Paste the JWT issuer (user:...):"
ask_secret AMO_JWT_SECRET "Paste the JWT secret:"
write_env AMO_JWT_ISSUER "$AMO_JWT_ISSUER"

# ── 9 ─────────────────────────────────────────────────────────────────────
stage "The six repo secrets"
say "These are the exact names release.yml maps onto the submit tool's environment."
set_secret CWS_EXTENSION_ID "$CWS_EXTENSION_ID"
set_secret CWS_PUBLISHER_ID "$CWS_PUBLISHER_ID"
set_secret CWS_SERVICE_ACCOUNT_EMAIL "$CWS_SERVICE_ACCOUNT_EMAIL"
set_secret CWS_SERVICE_ACCOUNT_PRIVATE_KEY "$CWS_SERVICE_ACCOUNT_PRIVATE_KEY"
set_secret AMO_JWT_ISSUER "$AMO_JWT_ISSUER"
set_secret AMO_JWT_SECRET "$AMO_JWT_SECRET"
say ""
say "Check all six landed:"
gh secret list --repo "$REPO" 2>/dev/null || warn "could not list secrets; check them in the repo settings"
pause "All six there?"

# ── 10 ────────────────────────────────────────────────────────────────────
stage "Cut extension-v1.0.0"
say "1.0.0 is deliberate: semantic-release only leaves 0.x on a breaking-change footer (§14.1)."
say "The commit must touch a path the extension stream watches — extension/, src/protocol/,"
say "src/page/ or skills/coachemon/scripts/hud/ — or no extension release is cut at all."
say ""
say "  git commit -m 'feat(extension): list Coachemon on the Chrome Web Store and AMO' \\"
say "             -m 'BREAKING CHANGE: first listed release'"
say ""
warn "This is the irreversible one: the release job uploads to both stores and submits for review."
if confirm "Push to master now?"; then
  git push origin master || warn "push failed; push by hand"
else
  note "fine — push when ready; the rest of this wizard is what happens afterwards"
fi
open_url "https://github.com/$REPO/actions/workflows/release.yml"
step "Watch the release-extension job. It stamps 1.0.0, builds, uploads and submits."
note "If it fails in verifyRelease, a credential is missing — re-run this wizard, nothing was published."
pause "Job finished?"

# ── 11 ────────────────────────────────────────────────────────────────────
stage "AMO: complete the listing"
say "CI's upload created the add-on and attached the sources zip. The metadata is still empty."
open_url "https://addons.mozilla.org/developers/addons"
open_url "file://$DOCS/docs/listing/store-disclosure.md"
step "Open Coachemon → Edit listing: name, summary and description from description.md,"
step "  category Games, the five tags, English, homepage and support email."
step "Licence: GNU Affero General Public License v3.0 only."
step "Data collection: required none, optional website content — it matches the manifest's declaration."
step "Privacy policy URL: https://iixauii.github.io/coachemon/PRIVACY"
step "Notes to reviewer: paste the AMO row from store-disclosure.md, including the 127.0.0.1:47147 line"
step "  and the three build lines (Node >= 23.6; cd extension && npm ci && npx wxt build -b firefox --mode store)."
pause "Listing saved?"

# ── 12 ────────────────────────────────────────────────────────────────────
stage "While the reviews run"
say "Firefox signs in about a day. Chrome takes days to weeks, with no expedite."
say ""
say "When both listings are public:"
step "The flip off CDP and Apple Events unblocks — that is its only gate."
open_url "https://github.com/$REPO/issues/210"
say ""
say "Safari is a separate path and does not gate anything here: a Developer ID-signed,"
say "notarized download, cut by 'npm run release:safari -- <version>'."
if confirm "Enrol in the Apple Developer Program now (\$99/year, takes days)?"; then
  open_url "https://developer.apple.com/programs/enroll/"
  step "Enrol as an individual, then follow docs/runbooks/safari-release.md's one-time setup."
  open_url "https://github.com/$REPO/issues/240"
else
  note "#240 keeps waiting on the membership; nothing else does"
fi
pause "Done here?"

finish
