// GENERATED by scripts/gen-enums.ts — do not edit.
// Source: pagefaultgames/pokerogue at v1.12.0.11.

export const GENERATED_GAME_VERSION = "1.12.0.11";

export const Button = {
  UP: 0,
  DOWN: 1,
  LEFT: 2,
  RIGHT: 3,
  SUBMIT: 4,
  ACTION: 5,
  CANCEL: 6,
  MENU: 7,
  STATS: 8,
  CYCLE_SHINY: 9,
  CYCLE_FORM: 10,
  CYCLE_GENDER: 11,
  CYCLE_ABILITY: 12,
  CYCLE_NATURE: 13,
  CYCLE_TERA: 14,
  SPEED_UP: 15,
  SLOW_DOWN: 16,
  DEV_CUSTOM: 17,
} as const;
export type Button = (typeof Button)[keyof typeof Button];

export const UiMode = {
  MESSAGE: 0,
  TITLE: 1,
  COMMAND: 2,
  FIGHT: 3,
  BALL: 4,
  TARGET_SELECT: 5,
  MODIFIER_SELECT: 6,
  SAVE_SLOT: 7,
  PARTY: 8,
  SUMMARY: 9,
  STARTER_SELECT: 10,
  EVOLUTION_SCENE: 11,
  EGG_HATCH_SCENE: 12,
  EGG_HATCH_SUMMARY: 13,
  CONFIRM: 14,
  OPTION_SELECT: 15,
  MENU: 16,
  MENU_OPTION_SELECT: 17,
  SETTINGS: 18,
  SETTINGS_DISPLAY: 19,
  SETTINGS_AUDIO: 20,
  SETTINGS_GAMEPAD: 21,
  GAMEPAD_BINDING: 22,
  SETTINGS_KEYBOARD: 23,
  KEYBOARD_BINDING: 24,
  ACHIEVEMENTS: 25,
  GAME_STATS: 26,
  EGG_LIST: 27,
  EGG_GACHA: 28,
  POKEDEX: 29,
  POKEDEX_SCAN: 30,
  POKEDEX_PAGE: 31,
  LOGIN_OR_REGISTER: 32,
  LOGIN_FORM: 33,
  REGISTRATION_FORM: 34,
  LOADING: 35,
  UNAVAILABLE: 36,
  CHALLENGE_SELECT: 37,
  RENAME_POKEMON: 38,
  RENAME_RUN: 39,
  RUN_HISTORY: 40,
  RUN_INFO: 41,
  TEST_DIALOGUE: 42,
  AUTO_COMPLETE: 43,
  ADMIN: 44,
  MYSTERY_ENCOUNTER: 45,
  CHANGE_PASSWORD_FORM: 46,
  ALERT_MODAL: 47,
} as const;
export type UiMode = (typeof UiMode)[keyof typeof UiMode];

export const PartyUiMode = {
  SWITCH: 0,
  FAINT_SWITCH: 1,
  POST_BATTLE_SWITCH: 2,
  REVIVAL_BLESSING: 3,
  MODIFIER: 4,
  MOVE_MODIFIER: 5,
  TM_MODIFIER: 6,
  REMEMBER_MOVE_MODIFIER: 7,
  MODIFIER_TRANSFER: 8,
  SPLICE: 9,
  RELEASE: 10,
  CHECK: 11,
  SELECT: 12,
  DISCARD: 13,
} as const;
export type PartyUiMode = (typeof PartyUiMode)[keyof typeof PartyUiMode];

export const BiomeId = {
  TOWN: 0,
  PLAINS: 1,
  GRASS: 2,
  TALL_GRASS: 3,
  METROPOLIS: 4,
  FOREST: 5,
  SEA: 6,
  SWAMP: 7,
  BEACH: 8,
  LAKE: 9,
  SEABED: 10,
  MOUNTAIN: 11,
  BADLANDS: 12,
  CAVE: 13,
  DESERT: 14,
  ICE_CAVE: 15,
  MEADOW: 16,
  POWER_PLANT: 17,
  VOLCANO: 18,
  GRAVEYARD: 19,
  DOJO: 20,
  FACTORY: 21,
  RUINS: 22,
  WASTELAND: 23,
  ABYSS: 24,
  SPACE: 25,
  CONSTRUCTION_SITE: 26,
  JUNGLE: 27,
  FAIRY_CAVE: 28,
  TEMPLE: 29,
  SLUM: 30,
  SNOWY_FOREST: 31,
  ISLAND: 40,
  LABORATORY: 41,
  END: 50,
} as const;
export type BiomeId = (typeof BiomeId)[keyof typeof BiomeId];

export const StatusEffect = {
  NONE: 0,
  POISON: 1,
  TOXIC: 2,
  PARALYSIS: 3,
  SLEEP: 4,
  FREEZE: 5,
  BURN: 6,
  FAINT: 7,
} as const;
export type StatusEffect = (typeof StatusEffect)[keyof typeof StatusEffect];

export const SaveSlotUiMode = {
  LOAD: 0,
  SAVE: 1,
} as const;
export type SaveSlotUiMode = (typeof SaveSlotUiMode)[keyof typeof SaveSlotUiMode];

export const SummaryUiMode = {
  DEFAULT: 0,
  LEARN_MOVE: 1,
} as const;
export type SummaryUiMode = (typeof SummaryUiMode)[keyof typeof SummaryUiMode];

export const PartyOption = {
  CANCEL: -1,
  SEND_OUT: 0,
  PASS_BATON: 1,
  REVIVE: 2,
  APPLY: 3,
  TEACH: 4,
  TRANSFER: 5,
  SUMMARY: 6,
  POKEDEX: 7,
  UNPAUSE_EVOLUTION: 8,
  SPLICE: 9,
  UNSPLICE: 10,
  RELEASE: 11,
  RENAME: 12,
  SELECT: 13,
  DISCARD: 14,
  SCROLL_UP: 1000,
  SCROLL_DOWN: 1001,
  FORM_CHANGE_ITEM: 2000,
  MOVE_1: 3000,
  MOVE_2: 3001,
  MOVE_3: 3002,
  MOVE_4: 3003,
  ALL: 4000,
} as const;
export type PartyOption = (typeof PartyOption)[keyof typeof PartyOption];

/** int → member name, for each table. */
export const NAMES = {
  Button: invert(Button),
  UiMode: invert(UiMode),
  PartyUiMode: invert(PartyUiMode),
  BiomeId: invert(BiomeId),
  StatusEffect: invert(StatusEffect),
  SaveSlotUiMode: invert(SaveSlotUiMode),
  SummaryUiMode: invert(SummaryUiMode),
  PartyOption: invert(PartyOption),
} as const;

function invert(table: Record<string, number>): Record<number, string> {
  const out: Record<number, string> = {};
  for (const [k, v] of Object.entries(table)) out[v] = k;
  return out;
}
