/**
 * Enum codegen: `Button`, `UiMode` and the discriminator enums the server
 * resolves screens with, generated from the public PokéRogue source at the
 * pinned tag rather than hand-transcribed (#2).
 *
 *   npm run enums:gen                       # at the pin in src/escape-ladder/reviewed.json
 *   npm run enums:gen -- --version 1.12.0.12
 *   npm run enums:gen -- --source ../pokerogue
 *   npm run enums:gen -- --check           # fail if generated.ts has drifted from this generator
 *
 * `--check` is there for CI to run (#258): the output is a function of the pinned tag
 * and this file, so a hand-edit to `src/enums/generated.ts` — or a generator
 * change that was never re-run — is a red build rather than a silent revert at
 * the next generate.
 *
 * The pin is shared with the escape ladder: both resolve `v<gameVersion>` and
 * never fetch a default branch, because the repo's default is `beta` and its
 * tables already differ from the deployed build (#2).
 */
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { parseArgs } from "node:util";
import { parseEnum } from "../src/enums/parse.ts";

const RAW = "https://raw.githubusercontent.com/pagefaultgames/pokerogue";
const REVIEWED = new URL("../src/escape-ladder/reviewed.json", import.meta.url);
const OUT = new URL("../src/enums/generated.ts", import.meta.url);

/** Enum name → file it lives in. `enum X {}`, `const X = {} as const` and `Object.freeze({})` forms are parsed. */
const ENUMS: Record<string, string> = {
  Button: "src/enums/buttons.ts",
  UiMode: "src/enums/ui-mode.ts",
  PartyUiMode: "src/enums/party-ui-mode.ts",
  BiomeId: "src/enums/biome-id.ts",
  StatusEffect: "src/enums/status-effect.ts",
  SaveSlotUiMode: "src/ui/handlers/save-slot-select-ui-handler.ts",
  SummaryUiMode: "src/ui/handlers/summary-ui-handler.ts",
  PartyOption: "src/ui/handlers/party-ui-handler.ts",
  // The coach HUD's enums (#94). The game's build inlines enums as numbers, so no
  // names exist at runtime: `hud-bundle.mjs` injects the members the HUD names.
  AbilityAttr: "src/enums/ability-attr.ts",
  AbilityId: "src/enums/ability-id.ts",
  AiType: "src/enums/ai-type.ts",
  ArenaTagSide: "src/enums/arena-tag-side.ts",
  BattleType: "src/enums/battle-type.ts",
  BattlerIndex: "src/enums/battler-index.ts",
  BerryType: "src/enums/berry-type.ts",
  BiomePoolTier: "src/enums/biome-pool-tier.ts",
  Challenges: "src/enums/challenges.ts",
  ClassicFixedBossWaves: "src/enums/fixed-boss-waves.ts",
  Command: "src/enums/command.ts",
  EvoLevelThresholdKind: "src/enums/evo-level-threshold-kind.ts",
  Gender: "src/data/gender.ts",
  HitResult: "src/enums/hit-result.ts",
  ModifierPoolType: "src/enums/modifier-pool-type.ts",
  ModifierTier: "src/enums/modifier-tier.ts",
  MoveCategory: "src/enums/move-category.ts",
  MoveFlags: "src/enums/move-flags.ts",
  MoveId: "src/enums/move-id.ts",
  MovePriorityInBracket: "src/enums/move-priority-in-bracket.ts",
  MoveResult: "src/enums/move-result.ts",
  MoveTarget: "src/enums/move-target.ts",
  MoveUseMode: "src/enums/move-use-mode.ts",
  MultiHitType: "src/enums/multi-hit-type.ts",
  MysteryEncounterOptionMode: "src/enums/mystery-encounter-option-mode.ts",
  MysteryEncounterTier: "src/enums/mystery-encounter-tier.ts",
  MysteryEncounterType: "src/enums/mystery-encounter-type.ts",
  Nature: "src/enums/nature.ts",
  Passive: "src/enums/passive.ts",
  PokeballType: "src/enums/pokeball.ts",
  PokemonType: "src/enums/pokemon-type.ts",
  SpeciesId: "src/enums/species-id.ts",
  Stat: "src/enums/stat.ts",
  TerrainType: "src/data/terrain.ts",
  TimeOfDay: "src/enums/time-of-day.ts",
  TrainerPoolTier: "src/enums/trainer-pool-tier.ts",
  TrainerSlot: "src/enums/trainer-slot.ts",
  WeatherType: "src/enums/weather-type.ts",
};

const { values: args } = parseArgs({
  options: { version: { type: "string" }, source: { type: "string" }, check: { type: "boolean" } },
});

const reviewed = JSON.parse(readFileSync(REVIEWED, "utf8")) as { pinned: { gameVersion: string } };
const version = args.version ?? reviewed.pinned.gameVersion;
const tag = `v${version}`;

async function read(file: string): Promise<string> {
  if (args.source) return readFileSync(path.join(path.resolve(args.source), file), "utf8");
  const cache = path.resolve(".cache/pokerogue-src", tag, file);
  if (existsSync(cache)) return readFileSync(cache, "utf8");
  const res = await fetch(`${RAW}/${tag}/${file}`);
  if (!res.ok) throw new Error(`${res.status} fetching ${file} at ${tag}`);
  const text = await res.text();
  mkdirSync(path.dirname(cache), { recursive: true });
  writeFileSync(cache, text);
  return text;
}

const parsed: Record<string, [string, number][]> = {};
for (const [name, file] of Object.entries(ENUMS)) parsed[name] = parseEnum(await read(file), name);

const lines: string[] = [
  "// GENERATED by scripts/gen-enums.ts — do not edit.",
  `// Source: pagefaultgames/pokerogue at ${tag}.`,
  "",
  `export const GENERATED_GAME_VERSION = ${JSON.stringify(version)};`,
  "",
];
for (const [name, members] of Object.entries(parsed)) {
  lines.push(`export const ${name} = {`);
  for (const [k, v] of members) lines.push(`  ${k}: ${v},`);
  lines.push("} as const;", `export type ${name} = (typeof ${name})[keyof typeof ${name}];`, "");
}
lines.push(
  "/** int → member name, for each table. */",
  "export const NAMES = {",
  ...Object.keys(parsed).map(name => `  ${name}: invert(${name}),`),
  "} as const;",
  "",
  "function invert(table: Record<string, number>): Record<number, string> {",
  "  const out: Record<number, string> = {};",
  "  for (const [k, v] of Object.entries(table)) out[v] = k;",
  "  return out;",
  "}",
  "",
);
const text = lines.join("\n");
const rel = path.relative(process.cwd(), new URL(OUT).pathname);
const counts = Object.entries(parsed).map(([n, m]) => `${n}=${m.length}`).join(", ");
if (args.check) {
  if (!existsSync(OUT) || readFileSync(OUT, "utf8") !== text) {
    console.error(`${rel} is stale — run \`npm run enums:gen\``);
    process.exit(1);
  }
  console.log(`${rel} up to date at ${tag}: ${counts}`);
} else {
  mkdirSync(path.dirname(new URL(OUT).pathname), { recursive: true });
  writeFileSync(OUT, text);
  console.log(`wrote ${rel} from ${tag}: ${counts}`);
}
