/**
 * Enum codegen: `Button`, `UiMode` and the discriminator enums the server
 * resolves screens with, generated from the public PokéRogue source at the
 * pinned tag rather than hand-transcribed (#2).
 *
 *   npm run enums:gen                       # at the pin in src/escape-ladder/reviewed.json
 *   npm run enums:gen -- --version 1.12.0.12
 *   npm run enums:gen -- --source ../pokerogue
 *
 * The pin is shared with the escape ladder: both resolve `v<gameVersion>` and
 * never fetch a default branch, because the repo's default is `beta` and its
 * tables already differ from the deployed build (#2).
 */
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { parseArgs } from "node:util";
import { parseEnum } from "../src/enums/parse.ts";

const RAW = "https://raw.githubusercontent.com/pagefaultgames/pokerogue";
const REVIEWED = new URL("../src/escape-ladder/reviewed.json", import.meta.url);
const OUT = new URL("../src/enums/generated.ts", import.meta.url);

/** Enum name → file it lives in. Both `enum X {}` and `const X = {} as const` forms are parsed. */
const ENUMS: Record<string, string> = {
  Button: "src/enums/buttons.ts",
  UiMode: "src/enums/ui-mode.ts",
  PartyUiMode: "src/enums/party-ui-mode.ts",
  BiomeId: "src/enums/biome-id.ts",
  StatusEffect: "src/enums/status-effect.ts",
  SaveSlotUiMode: "src/ui/handlers/save-slot-select-ui-handler.ts",
  SummaryUiMode: "src/ui/handlers/summary-ui-handler.ts",
  PartyOption: "src/ui/handlers/party-ui-handler.ts",
};

const { values: args } = parseArgs({
  options: { version: { type: "string" }, source: { type: "string" } },
});

const reviewed = JSON.parse(readFileSync(REVIEWED, "utf8")) as { pinned: { gameVersion: string } };
const version = args.version ?? reviewed.pinned.gameVersion;
const tag = `v${version}`;

async function read(file: string): Promise<string> {
  if (args.source) return readFileSync(path.join(path.resolve(args.source), file), "utf8");
  const cache = path.resolve(".cache/pokerogue-src", tag, file);
  if (existsSync(cache)) return readFileSync(cache, "utf8");
  const res = await fetch(`${RAW}/${tag}/${file}`);
  if (!res.ok) throw new Error(`${res.status} fetching ${file} at ${tag}`);
  const text = await res.text();
  mkdirSync(path.dirname(cache), { recursive: true });
  writeFileSync(cache, text);
  return text;
}

const parsed: Record<string, [string, number][]> = {};
for (const [name, file] of Object.entries(ENUMS)) parsed[name] = parseEnum(await read(file), name);

const lines: string[] = [
  "// GENERATED by scripts/gen-enums.ts — do not edit.",
  `// Source: pagefaultgames/pokerogue at ${tag}.`,
  "",
  `export const GENERATED_GAME_VERSION = ${JSON.stringify(version)};`,
  "",
];
for (const [name, members] of Object.entries(parsed)) {
  lines.push(`export const ${name} = {`);
  for (const [k, v] of members) lines.push(`  ${k}: ${v},`);
  lines.push("} as const;", `export type ${name} = (typeof ${name})[keyof typeof ${name}];`, "");
}
lines.push(
  "/** int → member name, for each table. */",
  "export const NAMES = {",
  ...Object.keys(parsed).map(name => `  ${name}: invert(${name}),`),
  "} as const;",
  "",
  "function invert(table: Record<string, number>): Record<number, string> {",
  "  const out: Record<number, string> = {};",
  "  for (const [k, v] of Object.entries(table)) out[v] = k;",
  "  return out;",
  "}",
  "",
);
mkdirSync(path.dirname(new URL(OUT).pathname), { recursive: true });
writeFileSync(OUT, lines.join("\n"));
console.log(`wrote ${path.relative(process.cwd(), new URL(OUT).pathname)} from ${tag}: ${Object.entries(parsed).map(([n, m]) => `${n}=${m.length}`).join(", ")}`);
