/**
 * Game code each coach HUD module leans on, hand-curated and hashed by `npm run drift:check`
 * (0001-escape-ladder-hand-curated-checked-at-pin-bump.md). A ref is listed whether the module calls it, re-implements
 * it or replays it in order, and a moved hash names only the module that reads it, never the modules built on it.
 */
import type { SourceRef } from "../src/escape-ladder/types.ts";

const P = "src/field/pokemon.ts";
const M = "src/data/moves/move.ts";
const SCENE = "src/battle-scene.ts";

export const HUD_DEPS = {
  /** game-code.md §0. */
  "01-core.js": [
    `src/data/abilities/apply-ab-attrs.ts#applySingleAbAttrs`,
    `src/battle.ts#Battle.randSeedInt`,
    `${SCENE}#BattleScene.executeWithSeedOffset`,
    `src/data/moves/move-utils.ts#getMoveTargets`,
    `${M}#ShellSideArmCategoryAttr.apply`,
    `${M}#PresentPowerAttr.apply`,
    `src/data/abilities/ab-attrs.ts#FullHpResistTypeAbAttr.apply`,
  ],

  /** game-code.md §10, §12. */
  "03-calendar.js": [
    `src/game-mode.ts#GameMode.isWaveFinal`,
    `src/game-mode.ts#GameMode.isFixedBattle`,
    `src/game-mode.ts#GameMode.isBoss`,
    `src/game-mode.ts#GameMode.isWaveTrainer`,
    `${SCENE}#BattleScene.handleNonFixedBattle`,
    `src/data/daily-seed/daily-run.ts#getDailyTrainerManipulation`,
    `src/utils/common.ts#randSeedInt`,
    `src/battle.ts#getRandomTrainerFunc`,
    `src/utils/common.ts#randInt`,
    `src/field/arena.ts#Arena.updatePoolsForTimeOfDay`,
    `${SCENE}#BattleScene.newArena`,
    `${SCENE}#BattleScene.doPostBattleCleanup`,
    `src/phases/switch-biome-phase.ts#SwitchBiomePhase.start`,
    `src/data/trainers/fixed-battle-configs.ts#classicFixedBattles`,
    `src/phases/victory-phase.ts#VictoryPhase.start`,
    `${SCENE}#BattleScene.isNewBiome`,
    `src/phases/select-biome-phase.ts#SelectBiomePhase.setNextBiomeAndEnd`,
    `src/phases/party-heal-phase.ts#PartyHealPhase.start`,
    `src/data/challenge.ts#LimitedSupportChallenge.applyPartyHeal`,
    `src/data/challenge.ts#HardcoreChallenge.applyPreventRevive`,
  ],

  /** game-code.md §2. */
  "07-move-traits.js": [
    `${M}#MoveAttr.constructor`,
    `src/data/moves/move-condition.ts#FirstMoveCondition.constructor`,
    `src/data/moves/move-condition.ts#consecutiveUseRestriction`,
    `${M}#RechargeAttr.constructor`,
    `${M}#PreUseInterruptAttr.apply`,
    `${M}#InstantChargeAttr.constructor`,
    `${M}#WeatherInstantChargeAttr.constructor`,
    `${M}#SemiInvulnerableAttr.apply`,
    `${M}#RecoilAttr.constructor`,
    `${M}#RecoilAttr.apply`,
    `${M}#HalfSacrificialAttr.apply`,
    `${M}#SacrificialAttr.apply`,
    `${M}#SacrificialAttrOnHit.apply`,
    `${M}#MissEffectAttr.apply`,
    `${M}#FrenzyAttr.apply`,
    `${M}#RemoveTypeAttr.apply`,
    `src/data/abilities/ab-attrs.ts#BlockNonDirectDamageAbAttr.constructor`,
    `src/data/abilities/ab-attrs.ts#BlockRecoilDamageAttr.apply`,
    `${M}#MultiHitAttr.getHitCount`,
    `${M}#MultiHitAttr.apply`,
    `${M}#MultiHitPowerIncrementAttr.apply`,
    `${M}#WaterShurikenMultiHitTypeAttr.apply`,
    `${M}#Move.canBeMultiStrikeEnhanced`,
    `src/data/abilities/ab-attrs.ts#MaxMultiHitAbAttr.apply`,
    `src/data/abilities/ab-attrs.ts#AddSecondStrikeAbAttr.canApply`,
    `src/modifier/modifier.ts#PokemonMultiHitModifier.apply`,
    `${M}#StatStageChangeAttr.constructor`,
    `${M}#CutHpStatStageBoostAttr.constructor`,
    `${M}#StatusEffectAttr.constructor`,
    `${M}#AddBattlerTagAttr.constructor`,
    `${M}#AddArenaTrapTagAttr.getCondition`,
    `${M}#HealAttr.constructor`,
    `${M}#BoostHealAttr.constructor`,
    `${M}#PlantHealAttr.getWeatherHealRatio`,
    `${M}#HitHealAttr.constructor`,
    `${M}#FlinchAttr.constructor`,
    `${M}#ProtectAttr.constructor`,
    `${M}#ChangeTypeAttr.constructor`,
    `${M}#AddTypeAttr.constructor`,
    `src/enums/multi-hit-type.ts#MultiHitType`,
    `src/enums/move-target.ts#MoveTarget`,
  ],

  /** game-code.md §1, §2, §3, §4, §5, §8, §18, §21. */
  "10-damage.js": [
    `${P}#Pokemon.getAttackDamage`,
    `${P}#Pokemon.calculateStabMultiplier`,
    `${M}#ModifiedDamageAttr.apply`,
    `${M}#SurviveDamageAttr.getModifiedDamage`,
    `${P}#Pokemon.getCriticalHitResult`,
    `${P}#Pokemon.getAccuracyMultiplier`,
    `${P}#Pokemon.getEffectiveStat`,
    `${P}#Pokemon.getMoveEffectiveness`,
    `${P}#Pokemon.damage`,
    `${P}#EnemyPokemon.damage`,
    `${P}#EnemyPokemon.handleBossSegmentCleared`,
    `src/utils/damage.ts#calculateBossSegmentDamage`,
    `${P}#Pokemon.heal`,
    `src/modifier/modifier.ts#PokemonInstantReviveModifier.apply`,
    `src/utils/common.ts#toDmgValue`,
    `src/phases/move-effect-phase.ts#MoveEffectPhase.hitCheck`,
    `src/phases/move-effect-phase.ts#MoveEffectPhase.checkBypassAccAndInvuln`,
    `${P}#Pokemon.getLastXMoves`,
    `${M}#PresentPowerAttr.apply`,
    `${M}#MultiHitAttr.getHitCount`,
    `${M}#Move.calculateBattleAccuracy`,
    `${SCENE}#BattleScene.getEncounterBossSegments`,
    `src/modifier/modifier.ts#SurviveDamageModifier.apply`,
    `src/modifier/modifier.ts#EnemyEndureChanceModifier.apply`,
    `src/data/abilities/ab-attrs.ts#FormBlockDamageAbAttr.apply`,
    `src/phases/turn-end-phase.ts#TurnEndPhase.start`,
    `${M}#MoveEffectAttr.getMoveChance`,
    `${M}#AddBattlerTagAttr.apply`,
    `src/field/arena.ts#Arena.isMoveWeatherCancelled`,
    `src/field/arena.ts#Arena.isMoveTerrainCancelled`,
    `src/phases/move-phase.ts#MovePhase.secondFailureCheck`,
    `src/phases/move-phase.ts#MovePhase.thirdFailureCheck`,
    `${M}#Move.doesFlagEffectApply`,
    `src/phases/move-effect-phase.ts#MoveEffectPhase.protectedCheck`,
    `${M}#HitHealAttr.apply`,
    `${M}#HitHealAttr.getHealAmount`,
    `src/phases/move-effect-phase.ts#MoveEffectPhase.applyMoveEffects`,
    `src/phases/move-effect-phase.ts#MoveEffectPhase.applyMoveDamage`,
    `src/phases/pokemon-heal-phase.ts#PokemonHealPhase.end`,
    `src/modifier/modifier.ts#HealingBoosterModifier.apply`,
    `src/data/abilities/ab-attrs.ts#ReverseDrainAbAttr.canApply`,
    `src/data/abilities/ab-attrs.ts#ReverseDrainAbAttr.apply`,
    `${P}#Pokemon.getMoveType`,
    `${P}#Pokemon.getMoveCategory`,
    `${P}#Pokemon.getCritStage`,
    `${M}#MultiHitAttr.apply`,
    `${M}#WaterShurikenMultiHitTypeAttr.apply`,
    `src/data/abilities/ab-attrs.ts#MaxMultiHitAbAttr.apply`,
    `src/data/abilities/ab-attrs.ts#AddSecondStrikeAbAttr.canApply`,
    `${M}#Move.canBeMultiStrikeEnhanced`,
    `src/modifier/modifier.ts#PokemonMultiHitModifier.apply`,
    `src/modifier/modifier.ts#PokemonMultiHitModifier.applyDamageModifier`,
    `src/phases/move-effect-phase.ts#MoveEffectPhase.start`,
    `src/phases/move-effect-phase.ts#MoveEffectPhase.conductHitChecks`,
    `src/phases/move-effect-phase.ts#MoveEffectPhase.end`,
    `${M}#MultiHitPowerIncrementAttr.apply`,
    `src/data/moves/move-utils.ts#getMoveTargets`,
    `${M}#PresentPowerAttr.apply`,
    `${M}#RandomLevelDamageAttr.getDamage`,
    `src/data/abilities/ab-attrs.ts#FullHpResistTypeAbAttr.apply`,
    `${P}#EnemyPokemon.getMinimumSegmentIndex`,
    `src/data/abilities/ab-attrs.ts#PreDefendFullHpEndureAbAttr.canApply`,
    `src/phase-manager.ts#turnEndPhases`,
    `src/phases/weather-effect-phase.ts#WeatherEffectPhase.start`,
    `src/data/weather.ts#Weather.isTypeDamageImmune`,
    `src/data/abilities/ab-attrs.ts#BlockWeatherDamageAttr.canApply`,
    `src/phases/berry-phase.ts#BerryPhase.eatBerries`,
    `src/data/berry.ts#getBerryPredicate`,
    `src/data/berry.ts#getBerryEffectFunc`,
    `src/phases/post-turn-status-effect-phase.ts#PostTurnStatusEffectPhase.start`,
    `src/modifier/modifier.ts#TurnStatusEffectModifier.apply`,
    `src/modifier/modifier.ts#TurnHealModifier.apply`,
    `src/modifier/modifier.ts#HitHealModifier.apply`,
    `src/modifier/modifier.ts#EnemyTurnHealModifier.apply`,
    `src/data/abilities/ab-attrs.ts#PostWeatherLapseDamageAbAttr.apply`,
    `src/data/abilities/ab-attrs.ts#PostWeatherLapseHealAbAttr.apply`,
    `src/data/abilities/ab-attrs.ts#PostTurnStatusHealAbAttr.apply`,
    `src/data/abilities/ab-attrs.ts#PostTurnHurtIfSleepingAbAttr.apply`,
    `${P}#Pokemon.getHpRatio`,
    // The TURN_END tags, each by class: one added upstream is in no hash here, and drops out of the turn-end number.
    `${P}#Pokemon.lapseTags`,
    `src/data/battler-tags.ts#SeedTag.lapse`,
    `src/data/battler-tags.ts#NightmareTag.lapse`,
    `src/data/battler-tags.ts#DamagingTrapTag.lapse`,
    `src/data/battler-tags.ts#SaltCuredTag.lapse`,
    `src/data/battler-tags.ts#CursedTag.lapse`,
    `src/data/battler-tags.ts#IngrainTag.lapse`,
    `src/data/battler-tags.ts#AquaRingTag.lapse`,
    `src/enums/move-flags.ts#MoveFlags`,
    // The restriction tags, each by class: one added upstream is in no hash here, and goes unnamed (#263).
    `src/data/moves/pokemon-move.ts#PokemonMove.isUsable`,
    `${P}#Pokemon.isMoveSelectable`,
    `src/data/battler-tags.ts#DisabledTag.isMoveRestricted`,
    `src/data/battler-tags.ts#TauntTag.isMoveRestricted`,
    `src/data/battler-tags.ts#EncoreTag.isMoveRestricted`,
    `src/data/battler-tags.ts#TormentTag.isMoveRestricted`,
    `src/data/battler-tags.ts#ImprisonTag.isMoveRestricted`,
    `src/data/battler-tags.ts#ThroatChoppedTag.isMoveRestricted`,
    `src/data/battler-tags.ts#HealBlockTag.isMoveRestricted`,
    `src/data/battler-tags.ts#GorillaTacticsTag.isMoveRestricted`,
  ],

  /** game-code.md §6, §7. */
  "20-enemy-ai.js": [
    `${P}#EnemyPokemon.getNextMove`,
    `${P}#EnemyPokemon.getNextTargets`,
    `src/phases/enemy-command-phase.ts#EnemyCommandPhase.start`,
    `${M}#Move.getTargetBenefitScore`,
    `${M}#Move.getUserBenefitScore`,
    `${M}#AttackMove.getTargetBenefitScore`,
    `${M}#StatStageChangeAttr.getTargetBenefitScore`,
    `src/battle.ts#Battle.randSeedInt`,
    `src/data/moves/move-utils.ts#getMoveTargets`,
    `src/battle.ts#Battle.incrementTurn`,
    `src/phases/command-phase.ts#CommandPhase.handleFightCommand`,
    `${M}#ProtectAttr.getCondition`,
    `src/enums/move-use-mode.ts#isVirtual`,
    `src/enums/move-use-mode.ts#isIgnorePP`,
    `${P}#Pokemon.getMoveType`,
    `${P}#Pokemon.getMatchupScore`,
    `${P}#Pokemon.isTrapped`,
    `src/field/trainer.ts#Trainer.getPartyMemberMatchupScores`,
    `src/field/trainer.ts#Trainer.getSortedPartyMemberMatchupScores`,
    `src/field/trainer.ts#Trainer.getNextSummonIndex`,
    `src/phases/switch-summon-phase.ts#SwitchSummonPhase.switchAndSummon`,
  ],

  /** game-code.md §0, §7, §14. */
  "25-turn.js": [
    `src/field/trainer.ts#Trainer.shouldTera`,
    `src/phases/tera-phase.ts#TeraPhase.end`,
    `src/phases/enemy-command-phase.ts#EnemyCommandPhase.start`,
    `${P}#Pokemon.getTypes`,
    `${P}#Pokemon.getBaseTypes`,
    `${M}#ChangeTypeAttr.apply`,
    `${M}#AddTypeAttr.apply`,
    `src/phases/turn-init-phase.ts#TurnInitPhase.start`,
    `${M}#Move.getPriority`,
    `${M}#Move.getPriorityModifier`,
    `${P}#Pokemon.getEffectiveStat`,
    `${P}#Pokemon.canSetStatus`,
    `${P}#Pokemon.getAttackTypeEffectiveness`,
    `${P}#Pokemon.isOfType`,
    `${M}#StatStageChangeAttr.getLevels`,
    `src/data/abilities/ab-attrs.ts#StatStageChangeMultiplierAbAttr.apply`,
    `${P}#Pokemon.getStatStage`,
    `src/data/weather.ts#getEffectiveWeatherForMove`,
    `src/data/abilities/ab-attrs.ts#PreAttackWeatherOverrideAbAttr.apply`,
    `${P}#Pokemon.getMatchupScore`,
  ],

  /** game-code.md §5, §9, §18. */
  "30-planner.js": [
    `${M}#MoveAttr.getUserBenefitScore`,
    `${M}#MoveAttr.getTargetBenefitScore`,
    `${M}#Move.getUserBenefitScore`,
    `${M}#Move.getTargetBenefitScore`,
    `src/utils/speed-order.ts#sortInSpeedOrder`,
    `src/modifier/modifier.ts#BypassSpeedChanceModifier.apply`,
    `src/phases/turn-start-phase.ts#TurnStartPhase.start`,
    `${P}#Pokemon.isTrapped`,
    `src/phases/check-switch-phase.ts#CheckSwitchPhase.start`,
    `src/phases/encounter-phase.ts#EncounterPhase.end`,
    `src/data/abilities/ab-attrs.ts#ForceSwitchOutHelper.switchOutLogic`,
    `${P}#Pokemon.resetSummonData`,
    `src/phases/switch-summon-phase.ts#SwitchSummonPhase.onEnd`,
    `src/phases/turn-end-phase.ts#TurnEndPhase.start`,
    `src/phases/move-phase.ts#MovePhase.checkPara`,
    `src/data/status-effect.ts#Status.incrementTurn`,
    `${M}#ProtectAttr.getCondition`,
    `${M}#ChangeTypeAttr.getCondition`,
    `${M}#AddTypeAttr.getCondition`,
    `${M}#StatStageChangeAttr.apply`,
    `${M}#CutHpStatStageBoostAttr.apply`,
    `${M}#StatusEffectAttr.apply`,
    `${M}#HealAttr.apply`,
    `${M}#PlantHealAttr.getWeatherHealRatio`,
    `${M}#SandHealAttr.getWeatherHealRatio`,
    `src/data/arena-tag.ts#EntryHazardTag.apply`,
    `src/data/arena-tag.ts#DamagingTrapTag.activateTrap`,
    `src/data/arena-tag.ts#SpikesTag.getDamageHpRatio`,
    `src/data/arena-tag.ts#StealthRockTag.getDamageHpRatio`,
    `src/data/arena-tag.ts#ToxicSpikesTag.activateTrap`,
    `src/phases/faint-phase.ts#FaintPhase.doFaint`,
    `src/data/abilities/ab-attrs.ts#PostVictoryStatStageChangeAbAttr.apply`,
    `src/data/abilities/ab-attrs.ts#PostKnockOutStatStageChangeAbAttr.apply`,
    `src/data/abilities/init-abilities.ts#beastBoostHighestStatCalc`,
    `src/phases/turn-start-phase.ts#TurnStartPhase.getCommandOrder`,
    `src/queues/move-phase-priority-queue.ts#MovePhasePriorityQueue.sortPostSpeed`,
    `src/data/abilities/ab-attrs.ts#BypassSpeedChanceAbAttr.canApply`,
    `src/data/battler-tags.ts#BypassSpeedTag.canAdd`,
    `src/data/abilities/ab-attrs.ts#PreventBypassSpeedChanceAbAttr.canApply`,
    `src/utils/common.ts#randSeedShuffle`,
    `${SCENE}#BattleScene.executeWithSeedOffset`,
    `src/queues/priority-queue.ts#PriorityQueue.pop`,
    `${P}#Pokemon.doSetStatus`,
    `src/phases/move-phase.ts#MovePhase.checkSleep`,
    `src/data/abilities/ab-attrs.ts#ReduceStatusEffectDurationAbAttr.apply`,
    `${M}#BoostHealAttr.constructor`,
  ],

  "35-team-plan.js": [
    `${P}#Pokemon.getMatchupScore`,
    `src/field/trainer.ts#Trainer.getPartyMemberMatchupScores`,
    `src/field/trainer.ts#Trainer.getNextSummonIndex`,
  ],

  "08-party.js": [
    `src/modifier/modifier-type.ts#getPartyLuckValue`,
    `${SCENE}#BattleScene.executeWithSeedOffset`,
    `src/utils/common.ts#randSeedInt`,
    `src/data/daily-seed/daily-run.ts#getDailyEventSeedLuck`,
    `src/timed-event-manager.ts#TimedEventManager.getEventLuckBoost`,
    `src/timed-event-manager.ts#TimedEventManager.getEventLuckBoostedSpecies`,
    `${P}#Pokemon.getLuck`,
    `${P}#Pokemon.isAllowedInBattle`,
    `${P}#Pokemon.calculateBaseStats`,
    `src/data/pokemon-species.ts#PokemonSpecies.getEvolutionLevels`,
    `src/data/pokemon-species.ts#PokemonSpeciesForm.getRootSpeciesId`,
  ],

  /** game-code.md §24. */
  "09-combatant.js": [
    `${P}#Pokemon.calculateStats`,
    `${P}#Pokemon.getAbility`,
    `${P}#Pokemon.hasPassive`,
    `${P}#Pokemon.getTypes`,
    `src/data/pokemon-species.ts#PokemonSpeciesForm.getAbility`,
    `src/data/abilities/ab-attrs.ts#PreDefendFullHpEndureAbAttr.canApply`,
  ],

  /** game-code.md §13. */
  "44-safari.js": [
    `src/data/mystery-encounters/encounters/safari-zone-encounter.ts#summonSafariPokemon`,
    `src/data/mystery-encounters/encounters/safari-zone-encounter.ts#getSafariSpeciesSpawn`,
    `src/data/mystery-encounters/encounters/safari-zone-encounter.ts#NUM_SAFARI_ENCOUNTERS`,
    `src/data/mystery-encounters/utils/encounter-phase-utils.ts#getRandomEncounterPokemon`,
    `src/data/mystery-encounters/utils/encounter-pokemon-utils.ts#getRandomSpeciesByStarterCost`,
    `src/data/balance/special-species-groups.ts#NON_LEGEND_PARADOX_POKEMON`,
    `src/data/balance/rates.ts#BASE_SHINY_CHANCE`,
    `src/data/balance/rates.ts#BASE_HIDDEN_ABILITY_RATE`,
    `${P}#Pokemon.trySetShinySeed`,
    `${P}#Pokemon.tryRerollHiddenAbilitySeed`,
    `${SCENE}#BattleScene.addEnemyPokemon`,
    `${SCENE}#BattleScene.executeWithSeedOffset`,
    `src/battle.ts#Battle.getLevelForWave`,
    `src/timed-event-manager.ts#TimedEventManager.getAllValidEventEncounters`,
    `src/utils/common.ts#randSeedItem`,
  ],

  /** game-code.md §20. */
  "45-catch.js": [
    `src/phases/attempt-capture-phase.ts#AttemptCapturePhase.start`,
    `src/data/pokeball.ts#getCriticalCaptureChance`,
    `src/phases/command-phase.ts#CommandPhase.checkCanUseBall`,
    `${P}#Pokemon.isShiny`,
    `src/system/game-data.ts#GameData.setPokemonSpeciesCaught`,
    `src/timed-event-manager.ts#TimedEventManager.getShinyCatchMultiplier`,
    `src/data/moves/move.ts#SurviveDamageAttr.getModifiedDamage`,
    `src/data/pokeball.ts#getPokeballCatchMultiplier`,
    `src/data/status-effect.ts#getStatusEffectCatchRateMultiplier`,
    `src/modifier/modifier.ts#CriticalCatchChanceBoosterModifier.apply`,
    `src/phases/command-phase.ts#CommandPhase.handleBallCommand`,
    `${P}#Pokemon.hasAbility`,
    `src/game-mode.ts#GameMode.isBattleClassicFinalBoss`,
    `src/game-mode.ts#GameMode.isEndlessMinorBoss`,
    `src/game-mode.ts#GameMode.isFullFreshStartChallenge`,
    `src/game-mode.ts#GameMode.isFreshStartChallenge`,
    `src/game-mode.ts#GameMode.hasAnyChallenges`,
    `src/game-mode.ts#GameMode.isWaveFinal`,
    `src/data/daily-seed/daily-run.ts#getDailyEventSeedBoss`,
    `src/data/daily-seed/daily-seed-utils.ts#isDailyFinalBoss`,
    `src/system/game-data.ts#GameData.getStarterCount`,
    `src/phases/attempt-capture-phase.ts#AttemptCapturePhase.catch`,
    `src/data/challenge.ts#LimitedCatchChallenge.applyPokemonAddToParty`,
    `${P}#Pokemon.getDexAttr`,
    `src/data/pokemon-species.ts#PokemonSpeciesForm.getRootSpeciesId`,
    `src/data/pokemon-species.ts#PokemonSpecies.getFullUnlocksData`,
    `src/data/species-data-registry.ts#SpeciesDataRegistry.getSpecies`,
  ],

  "40-learn.js": [
    `${P}#Pokemon.getBaseDamage`,
    `${M}#PresentPowerAttr.apply`,
    `${P}#Pokemon.canSetStatus`,
    `${P}#Pokemon.getMoveEffectiveness`,
    `${M}#Move.isTypeImmune`,
    `src/data/abilities/init-abilities.ts#initAbilities`,
    `src/data/battler-tags.ts#TauntTag.isMoveRestricted`,
    `src/data/battler-tags.ts#HealBlockTag.isMoveRestricted`,
    `src/data/battler-tags.ts#EncoreTag.canAdd`,
    `src/data/moves/invalid-moves.ts#healBlockedMoves`,
    `src/enums/move-target.ts#MoveTarget`,
    `src/enums/status-effect.ts#StatusEffect`,
    `src/enums/battler-tag-type.ts#BattlerTagType`,
  ],

  /** game-code.md §13. */
  "46-encounter.js": [
    `src/ui/handlers/mystery-encounter-ui-handler.ts#MysteryEncounterUiHandler.displayEncounterOptions`,
    `src/ui/handlers/mystery-encounter-ui-handler.ts#MysteryEncounterUiHandler.processInput`,
    `src/phases/mystery-encounter-phases.ts#MysteryEncounterPhase.start`,
    `src/phases/mystery-encounter-phases.ts#MysteryEncounterPhase.handleOptionSelect`,
    `src/phases/mystery-encounter-phases.ts#MysteryEncounterOptionSelectedPhase.start`,
    `src/phases/mystery-encounter-phases.ts#PostMysteryEncounterPhase.start`,
    `src/phases/mystery-encounter-phases.ts#MysteryEncounterRewardsPhase.doEncounterRewardsAndContinue`,
    `src/data/mystery-encounters/mystery-encounter.ts#MysteryEncounter.updateSeedOffset`,
    `${SCENE}#BattleScene.executeWithSeedOffset`,
    `src/utils/common.ts#randSeedInt`,
    `src/data/mystery-encounters/mystery-encounter-option.ts#MysteryEncounterOption.meetsRequirements`,
    `src/data/mystery-encounters/mystery-encounter-option.ts#MysteryEncounterOption.meetsPrimaryRequirementAndPrimaryPokemonSelected`,
    `src/data/mystery-encounters/mystery-encounter-requirements.ts#MoneyRequirement.meetsRequirement`,
    `src/data/mystery-encounters/requirements/requirement-groups.ts#STEALING_MOVES`,
    `src/data/mystery-encounters/requirements/requirement-groups.ts#CHARMING_MOVES`,
    `src/data/mystery-encounters/requirements/requirement-groups.ts#FIRE_RESISTANT_ABILITIES`,
    `src/data/mystery-encounters/utils/encounter-phase-utils.ts#leaveEncounterWithoutBattle`,
    `src/data/mystery-encounters/utils/encounter-phase-utils.ts#handleMysteryEncounterVictory`,
    `src/data/mystery-encounters/utils/encounter-phase-utils.ts#initBattleWithEnemyConfig`,
    `src/data/mystery-encounters/utils/encounter-pokemon-utils.ts#getHighestLevelPlayerPokemon`,
    `src/data/mystery-encounters/utils/encounter-pokemon-utils.ts#getEncounterPokemonLevelForWave`,
    `src/data/mystery-encounters/utils/encounter-pokemon-utils.ts#applyDamageToPokemon`,
    `src/data/mystery-encounters/utils/encounter-pokemon-utils.ts#modifyPlayerPokemonBST`,
    `src/modifier/modifier.ts#PokemonBaseStatTotalModifier.apply`,
    `src/modifier/modifier.ts#MoneyMultiplierModifier.apply`,
    `src/modifier/modifier.ts#MoneyMultiplierModifier.getMaxStackCount`,
    `${SCENE}#BattleScene.getWaveMoneyAmount`,
    `src/enums/mystery-encounter-type.ts#MysteryEncounterType`,
    `src/enums/mystery-encounter-tier.ts#MysteryEncounterTier`,
    `src/enums/nature.ts#Nature`,
    `src/data/mystery-encounters/encounters/mysterious-chest-encounter.ts#MysteriousChestEncounter`,
    `src/data/mystery-encounters/encounters/mysterious-chest-encounter.ts#TRAP_PERCENT`,
    `src/data/mystery-encounters/encounters/mysterious-chest-encounter.ts#COMMON_REWARDS_PERCENT`,
    `src/data/mystery-encounters/encounters/mysterious-chest-encounter.ts#ULTRA_REWARDS_PERCENT`,
    `src/data/mystery-encounters/encounters/mysterious-chest-encounter.ts#ROGUE_REWARDS_PERCENT`,
    `src/data/mystery-encounters/encounters/mysterious-chest-encounter.ts#MASTER_REWARDS_PERCENT`,
    `src/data/mystery-encounters/encounters/fight-or-flight-encounter.ts#FightOrFlightEncounter`,
    `src/data/mystery-encounters/encounters/department-store-sale-encounter.ts#DepartmentStoreSaleEncounter`,
    `src/data/mystery-encounters/encounters/shady-vitamin-dealer-encounter.ts#ShadyVitaminDealerEncounter`,
    `src/data/mystery-encounters/encounters/lost-at-sea-encounter.ts#LostAtSeaEncounter`,
    `src/data/mystery-encounters/encounters/lost-at-sea-encounter.ts#DAMAGE_PERCENTAGE`,
    `src/data/mystery-encounters/encounters/fiery-fallout-encounter.ts#FieryFalloutEncounter`,
    `src/data/mystery-encounters/encounters/fiery-fallout-encounter.ts#DAMAGE_PERCENTAGE`,
    `src/data/mystery-encounters/encounters/the-strong-stuff-encounter.ts#TheStrongStuffEncounter`,
    `src/data/mystery-encounters/encounters/berries-abound-encounter.ts#BerriesAboundEncounter`,
    `src/data/mystery-encounters/encounters/part-timer-encounter.ts#PartTimerEncounter`,
    `src/data/mystery-encounters/encounters/part-timer-encounter.ts#applyMoneyMultipliers`,
    `src/data/mystery-encounters/encounters/teleporting-hijinks-encounter.ts#TeleportingHijinksEncounter`,
    `src/data/mystery-encounters/encounters/teleporting-hijinks-encounter.ts#BIOME_CANDIDATES`,
    `src/data/mystery-encounters/encounters/teleporting-hijinks-encounter.ts#doBiomeTransitionDialogueAndBattleInit`,
    `src/data/mystery-encounters/encounters/uncommon-breed-encounter.ts#UncommonBreedEncounter`,
    `src/data/mystery-encounters/encounters/global-trade-system-encounter.ts#GlobalTradeSystemEncounter`,
    `src/data/mystery-encounters/encounters/global-trade-system-encounter.ts#getPokemonTradeOptions`,
    `src/data/mystery-encounters/encounters/mysterious-challengers-encounter.ts#MysteriousChallengersEncounter`,
    `src/data/mystery-encounters/encounters/slumbering-snorlax-encounter.ts#SlumberingSnorlaxEncounter`,
    `src/phases/party-heal-phase.ts#PartyHealPhase.start`,
    `src/data/mystery-encounters/encounters/safari-zone-encounter.ts#SafariZoneEncounter`,
    `src/data/mystery-encounters/encounters/safari-zone-encounter.ts#SAFARI_MONEY_MULTIPLIER`,
    `src/data/mystery-encounters/encounters/safari-zone-encounter.ts#NUM_SAFARI_ENCOUNTERS`,
    `src/data/mystery-encounters/encounters/safari-zone-encounter.ts#safariZoneGameOptions`,
    `src/data/mystery-encounters/encounters/safari-zone-encounter.ts#throwPokeball`,
    `src/data/mystery-encounters/encounters/safari-zone-encounter.ts#getSafariSpeciesSpawn`,
    `src/data/mystery-encounters/utils/encounter-pokemon-utils.ts#trainerThrowPokeball`,
    `src/data/mystery-encounters/encounters/safari-zone-encounter.ts#isPokemonFlee`,
    `src/data/mystery-encounters/encounters/safari-zone-encounter.ts#tryChangeCatchStage`,
    `src/data/mystery-encounters/encounters/safari-zone-encounter.ts#tryChangeFleeStage`,
    `src/data/mystery-encounters/encounters/safari-zone-encounter.ts#doEndTurn`,
    `src/data/mystery-encounters/encounters/safari-zone-encounter.ts#summonSafariPokemon`,
    `src/data/mystery-encounters/utils/encounter-phase-utils.ts#initSubsequentOptionSelect`,
    `src/data/mystery-encounters/encounters/delibirdy-encounter.ts#DelibirdyEncounter`,
    `src/data/mystery-encounters/encounters/delibirdy-encounter.ts#DELIBIRDY_MONEY_PRICE_MULTIPLIER`,
    `src/data/mystery-encounters/encounters/delibirdy-encounter.ts#OPTION_2_ALLOWED_MODIFIERS`,
    `src/data/mystery-encounters/encounters/delibirdy-encounter.ts#OPTION_3_DISALLOWED_MODIFIERS`,
    `src/modifier/modifier.ts#LevelIncrementBoosterModifier.getMaxStackCount`,
    `src/modifier/modifier.ts#PreserveBerryModifier.getMaxStackCount`,
    `src/modifier/modifier.ts#HealingBoosterModifier.getMaxStackCount`,
    `src/modifier/modifier.ts#MegaEvolutionAccessModifier.getMaxStackCount`,
    `src/modifier/modifier.ts#GigantamaxAccessModifier.getMaxStackCount`,
    `src/data/mystery-encounters/encounters/absolute-avarice-encounter.ts#AbsoluteAvariceEncounter`,
    `src/data/mystery-encounters/encounters/dancing-lessons-encounter.ts#DancingLessonsEncounter`,
    `src/data/mystery-encounters/requirements/requirement-groups.ts#DANCING_MOVES`,
    `src/data/mystery-encounters/encounters/bug-type-superfan-encounter.ts#BugTypeSuperfanEncounter`,
    `src/data/mystery-encounters/encounters/bug-type-superfan-encounter.ts#PHYSICAL_TUTOR_MOVES`,
    `src/data/mystery-encounters/encounters/bug-type-superfan-encounter.ts#SPECIAL_TUTOR_MOVES`,
    `src/data/mystery-encounters/encounters/bug-type-superfan-encounter.ts#STATUS_TUTOR_MOVES`,
    `src/data/mystery-encounters/encounters/bug-type-superfan-encounter.ts#MISC_TUTOR_MOVES`,
    `src/data/mystery-encounters/encounters/bug-type-superfan-encounter.ts#getTrainerConfigForWave`,
    `src/data/mystery-encounters/encounters/fun-and-games-encounter.ts#FunAndGamesEncounter`,
    `src/data/mystery-encounters/encounters/fun-and-games-encounter.ts#handleNextTurn`,
    `src/data/mystery-encounters/encounters/fun-and-games-encounter.ts#handleLoseMinigame`,
    `src/data/mystery-encounters/encounters/fun-and-games-encounter.ts#summonPlayerPokemon`,
    `src/data/mystery-encounters/encounters/training-session-encounter.ts#TrainingSessionEncounter`,
    `src/data/mystery-encounters/encounters/the-pokemon-salesman-encounter.ts#ThePokemonSalesmanEncounter`,
    `src/data/mystery-encounters/encounters/the-pokemon-salesman-encounter.ts#getSalesmanSpeciesOffer`,
    `src/data/mystery-encounters/encounters/trash-to-treasure-encounter.ts#TrashToTreasureEncounter`,
    `src/data/mystery-encounters/encounters/clowning-around-encounter.ts#ClowningAroundEncounter`,
    `src/data/mystery-encounters/encounters/the-expert-pokemon-breeder-encounter.ts#TheExpertPokemonBreederEncounter`,
    `src/data/mystery-encounters/encounters/dark-deal-encounter.ts#DarkDealEncounter`,
    `src/data/mystery-encounters/encounters/a-trainers-test-encounter.ts#ATrainersTestEncounter`,
    `src/data/mystery-encounters/encounters/weird-dream-encounter.ts#WeirdDreamEncounter`,
    `src/data/mystery-encounters/encounters/the-winstrate-challenge-encounter.ts#TheWinstrateChallengeEncounter`,
    `src/data/mystery-encounters/utils/encounter-pokemon-utils.ts#getRandomPlayerPokemon`,
    `src/utils/common.ts#randSeedShuffle`,
    `src/utils/pokemon-utils.ts#getRandomRegularPokemonType`,
    `src/data/trainers/trainer-config.ts#TrainerConfig.initForStatTrainer`,
    `src/data/trainers/trainer-party-template.ts#trainerPartyTemplates`,
    `src/data/trainers/trainer-party-template.ts#TrainerPartyCompoundTemplate.constructor`,
    `src/field/trainer.ts#Trainer.getPartyTemplate`,
    `src/field/trainer.ts#Trainer.getPartyLevels`,
  ],

  /** game-code.md §10. */
  "47-biome.js": [
    `src/phases/select-biome-phase.ts#SelectBiomePhase.start`,
    `src/field/arena.ts#Arena.randomSpecies`,
    `src/field/arena.ts#Arena.randomTrainerType`,
    `src/field/arena.ts#Arena.generateNonBossBiomeTier`,
    `src/field/arena.ts#Arena.generateBossBiomeTier`,
    `src/field/arena.ts#Arena.checkLegendBST`,
    `src/field/arena.ts#Arena.getTimeOfDay`,
    `src/game-mode.ts#GameMode.isTrainerBoss`,
    `src/game-mode.ts#GameMode.getWaveForDifficulty`,
    `src/data/daily-seed/daily-run.ts#getDailyForcedWaveBiomePoolTier`,
    `src/field/trainer.ts#Trainer.genNewPartyMemberSpecies`,
    `${SCENE}#BattleScene.randomSpecies`,
    `src/data/trainers/trainer-config.ts#TrainerConfig.initForGymLeader`,
    `src/ai/ai-species-gen.ts#determineEnemySpecies`,
    `src/ai/ai-species-gen.ts#calcEvoChance`,
    `src/ai/ai-species-gen.ts#getRequiredPrevo`,
    `src/field/arena.ts#Arena.updatePoolsForTimeOfDay`,
    `${SCENE}#BattleScene.getEncounterBossSegments`,
    `src/data/pokemon-species.ts#PokemonSpecies.getWildSpeciesForLevel`,
    `src/data/trainers/trainer-config.ts#TrainerConfig.constructor`,
  ],

  /** game-code.md §11. */
  "48-preview.js": [
    `${SCENE}#BattleScene.newBattle`,
    `${SCENE}#BattleScene.handleFixedBattle`,
    `${SCENE}#BattleScene.handleNonFixedBattle`,
    `${SCENE}#BattleScene.executeWithSeedOffset`,
    `${SCENE}#BattleScene.resetSeed`,
    `${SCENE}#BattleScene.isWaveMysteryEncounter`,
    `${SCENE}#BattleScene.generateNewBattleTrainer`,
    `${SCENE}#BattleScene.checkIsDouble`,
    `${SCENE}#BattleScene.getEncounterBossSegments`,
    `${SCENE}#BattleScene.randomSpecies`,
    `${SCENE}#BattleScene.addEnemyPokemon`,
    `${SCENE}#BattleScene.getMysteryEncounter`,
    `src/field/arena.ts#Arena.randomSpecies`,
    `src/game-mode.ts#GameMode.isFixedBattle`,
    `src/game-mode.ts#GameMode.getFixedBattle`,
    `src/game-mode.ts#GameMode.isWaveTrainer`,
    `src/game-mode.ts#GameMode.isBoss`,
    `src/field/arena.ts#Arena.getTimeOfDay`,
    `src/field/arena.ts#Arena.updatePoolsForTimeOfDay`,
    `src/field/trainer.ts#Trainer.constructor`,
    `src/field/trainer.ts#Trainer.genPartyMember`,
    `src/field/trainer.ts#Trainer.getPartyLevels`,
    `src/battle.ts#Battle.constructor`,
    `src/battle.ts#Battle.getLevelForWave`,
    `src/phases/encounter-phase.ts#EncounterPhase.start`,
    `src/phases/encounter-phase.ts#EncounterPhase.isEncounterShinyLocked`,
    `${P}#Pokemon.constructor`,
    `${P}#EnemyPokemon.constructor`,
    `src/utils/common.ts#shiftCharCodes`,
    `src/utils/common.ts#randSeedInt`,
  ],

  /** game-code.md §12, §16. */
  "49-ahead.js": [
    `src/game-mode.ts#GameMode.isFixedBattle`,
    `src/game-mode.ts#GameMode.getFixedBattle`,
    `src/modifier/modifier-type.ts#getNewModifierTypeOption`,
    `src/phases/select-modifier-phase.ts#SelectModifierPhase.getRerollCost`,
    `src/modifier/modifier-type.ts#getPlayerModifierTypeOptions`,
    `${SCENE}#BattleScene.initFinalBossPhaseTwo`,
    `${SCENE}#BattleScene.generateEnemyModifiers`,
    `${P}#Pokemon.hasPassive`,
    `${P}#EnemyPokemon.generateAndPopulateMoveset`,
    `${P}#EnemyPokemon.getMinimumSegmentIndex`,
    `src/data/moves/pokemon-move.ts#PokemonMove.getMovePp`,
    `src/phases/damage-anim-phase.ts#DamageAnimPhase.end`,
    `src/utils/common.ts#randInt`,
    `${SCENE}#BattleScene.checkIsDouble`,
    `${SCENE}#BattleScene.getDoubleBattleChance`,
    `${SCENE}#BattleScene.generateNewBattleTrainer`,
    `src/game-mode.ts#GameMode.isWaveFinal`,
    `src/game-mode.ts#GameMode.isEndlessBoss`,
    `src/modifier/modifier.ts#DoubleBattleChanceBoosterModifier.apply`,
    `src/modifier/modifier.ts#DoubleBattleChanceBoosterModifier.match`,
    `src/battle.ts#getRandomTrainerFunc`,
    `src/modifier/modifier.ts#LapsingPersistentModifier.lapse`,
    `src/phases/battle-end-phase.ts#BattleEndPhase.start`,
    `src/data/abilities/ab-attrs.ts#DoubleBattleChanceAbAttr.apply`,
  ],

  /** game-code.md §17. */
  "50-audit.js": [
    `${P}#Pokemon.getLearnableLevelMoves`,
    `src/modifier/modifier-type.ts#RememberMoveModifierType.constructor`,
    `src/modifier/modifier.ts#RememberMoveModifier.apply`,
    `${P}#Pokemon.canSetStatus`,
    `${M}#Move.getPriority`,
    `src/data/abilities/ab-attrs.ts#ChangeMovePriorityAbAttr.apply`,
    `src/utils/speed-order.ts#sortInSpeedOrder`,
    `${SCENE}#BattleScene.applyPartyExp`,
    `${SCENE}#BattleScene.getMaxExpLevel`,
  ],

  /** game-code.md §24. */
  "49-fusion.js": [
    `src/modifier/modifier-type.ts#FusePokemonModifierType.constructor`,
    `src/modifier/modifier.ts#FusePokemonModifier.apply`,
    `src/phases/select-modifier-phase.ts#SelectModifierPhase.openFusionMenu`,
    `src/ui/handlers/party-ui-handler.ts#PartyUiHandler.show`,
    `src/ui/handlers/party-ui-handler.ts#PartyUiHandler.getFilterResult`,
    `src/ui/handlers/party-ui-handler.ts#PartyUiHandler.processActionButtonForOptions`,
    `src/data/challenge.ts#HardcoreChallenge.applyPokemonFusion`,
    `${P}#PlayerPokemon.fuse`,
    `${P}#Pokemon.calculateBaseStats`,
    `${P}#Pokemon.calculateStats`,
    `${P}#Pokemon.getBaseTypes`,
    `${P}#Pokemon.getAbility`,
    `${P}#Pokemon.canApplyAbility`,
    `src/data/pokemon-species.ts#PokemonSpeciesForm.getAbility`,
    `src/modifier/init-modifier-pools.ts#initGreatModifierPool`,
    `src/modifier/init-modifier-pools.ts#initMasterModifierPool`,
  ],

  /** game-code.md §15. */
  "51-items.js": [
    `src/data/pokemon-species.ts#PokemonSpecies.getEvolutionLevels`,
    `src/modifier/modifier-type.ts#PokemonHeldItemModifierType.constructor`,
    `src/modifier/modifier-type.ts#PokemonNatureChangeModifierType.constructor`,
    `src/modifier/modifier-type.ts#EvolutionItemModifierType.constructor`,
    `src/modifier/modifier-type.ts#SpeciesStatBoosterModifierTypeGenerator.constructor`,
    `src/modifier/init-modifier-pools.ts#initUltraModifierPool`,
    `src/modifier/modifier.ts#TurnHealModifier.apply`,
    `src/modifier/modifier.ts#HitHealModifier.apply`,
    `src/modifier/modifier.ts#SurviveDamageModifier.apply`,
    `src/modifier/modifier.ts#CritBoosterModifier.apply`,
    `src/modifier/modifier.ts#FieldEffectModifier.apply`,
    `src/modifier/modifier.ts#ContactHeldItemTransferChanceModifier.getTransferredItemCount`,
    `src/phases/move-effect-phase.ts#MoveEffectPhase.applyOnTargetEffects`,
    `src/modifier/modifier.ts#PokemonMoveAccuracyBoosterModifier.apply`,
    `src/modifier/modifier.ts#BypassSpeedChanceModifier.apply`,
    `src/modifier/modifier.ts#FlinchChanceModifier.apply`,
    `src/modifier/modifier.ts#PokemonInstantReviveModifier.apply`,
    `src/modifier/modifier.ts#EvolutionStatBoosterModifier.apply`,
    `src/modifier/modifier.ts#PokemonMultiHitModifier.applyDamageModifier`,
    `src/modifier/modifier.ts#PokemonNatureWeightModifier.apply`,
    `src/modifier/modifier.ts#BaseStatModifier.getMaxHeldItemCount`,
    `src/modifier/modifier.ts#BerryModifier.getMaxHeldItemCount`,
    `src/modifier/modifier.ts#ExpShareModifier.apply`,
    `src/modifier/modifier.ts#PokemonLevelIncrementModifier.apply`,
    `${SCENE}#BattleScene.getMaxExpLevel`,
    `src/game-mode.ts#GameMode.getWaveForDifficulty`,
    `${SCENE}#BattleScene.applyPartyExp`,
    `${P}#PlayerPokemon.addExp`,
    `src/enums/nature.ts#Nature`,
    `src/enums/stat.ts#Stat`,
    `src/enums/berry-type.ts#BerryType`,
  ],

  /** game-code.md §19. */
  "50-reroll.js": [
    `src/phases/select-modifier-phase.ts#SelectModifierPhase.constructor`,
    `src/phases/select-modifier-phase.ts#SelectModifierPhase.start`,
    `src/phases/select-modifier-phase.ts#SelectModifierPhase.rerollModifiers`,
    `src/phases/select-modifier-phase.ts#SelectModifierPhase.toggleRerollLock`,
    `src/phases/select-modifier-phase.ts#SelectModifierPhase.getModifierCount`,
    `src/phases/select-modifier-phase.ts#SelectModifierPhase.getRerollCost`,
    `src/phases/select-modifier-phase.ts#SelectModifierPhase.getModifierTypeOptions`,
    `src/modifier/modifier-type.ts#regenerateModifierPoolThresholds`,
    `src/modifier/modifier-type.ts#getPlayerModifierTypeOptions`,
    `src/ui/handlers/modifier-select-ui-handler.ts#ModifierSelectUiHandler.show`,
  ],

  "55-journal.js": [
    `src/phases/mystery-encounter-phases.ts#MysteryEncounterPhase.start`,
    `src/phases/mystery-encounter-phases.ts#MysteryEncounterPhase.handleOptionSelect`,
    `src/data/mystery-encounters/mystery-encounter-save-data.ts#SeenEncounterData.constructor`,
  ],

  /** game-code.md §16. */
  "52-shop.js": [
    `src/game-mode.ts#GameMode.hasChallenge`,
    `src/modifier/modifier-type.ts#TmModifierType.constructor`,
    `src/modifier/modifier-type.ts#TmModifierTypeGenerator.constructor`,
    `${P}#PlayerPokemon.isTmCompatible`,
    `${P}#PlayerPokemon.getCompatibleTms`,
    `src/ui/handlers/party-ui-handler.ts#PartyUiHandler.updateOptions`,
    `src/ui/handlers/party-ui-handler.ts#PartyUiHandler.updateOptionsHardcore`,
    `src/enums/challenges.ts#Challenges`,
  ],

  /** game-code.md §23. */
  "51-starters.js": [
    `src/ui/handlers/starter-select-ui-handler.ts#StarterSelectUiHandler.show`,
    `src/ui/handlers/starter-select-ui-handler.ts#StarterSelectUiHandler.getValueLimit`,
    `src/ui/handlers/starter-select-ui-handler.ts#StarterSelectUiHandler.getSpeciesData`,
    `src/ui/handlers/starter-select-ui-handler.ts#StarterSelectUiHandler.getCurrentDexProps`,
    `src/ui/handlers/starter-select-ui-handler.ts#StarterSelectUiHandler.isPartyValid`,
    `src/ui/handlers/starter-select-ui-handler.ts#StarterSelectUiHandler.addToParty`,
    `src/utils/challenge-utils.ts#checkStarterValidForChallenge`,
    `src/system/game-data.ts#GameData.getSpeciesStarterValue`,
    `src/system/game-data.ts#GameData.getSpeciesDexAttrProps`,
    `src/system/game-data.ts#GameData.getDexAttrLuck`,
    `src/data/pokemon-species.ts#PokemonSpecies.getEvolutionLevels`,
    `src/data/pokemon-species.ts#PokemonSpeciesForm.getPassiveAbility`,
    `src/data/species-data-registry.ts#SpeciesDataRegistry.getEvolutions`,
    `src/phases/select-starter-phase.ts#SelectStarterPhase.start`,
    `src/game-mode.ts#GameMode.getStartingLevel`,
    `src/data/challenge.ts#SingleGenerationChallenge.applyStarterChoice`,
    `src/data/challenge.ts#SingleTypeChallenge.applyStarterChoice`,
    `src/data/challenge.ts#FreshStartChallenge.applyStarterChoice`,
    `src/data/challenge.ts#FreshStartChallenge.applyStarterCost`,
    `src/data/challenge.ts#FreshStartChallenge.applyStarterSelectModify`,
    `src/data/challenge.ts#LowerStarterMaxCostChallenge.applyStarterChoice`,
    `src/data/challenge.ts#LowerStarterPointsChallenge.applyStarterPoints`,
    `src/data/challenge.ts#InverseBattleChallenge.applyTypeEffectiveness`,
    `src/data/type.ts#getTypeDamageMultiplier`,
  ],
} satisfies Record<string, readonly SourceRef[]>;
